# Draw word cloud for translated English words generated by transWord.R
library(wordcloud)
library(tm)
library(RColorBrewer)

setwd("C:/Dropbox/Programming/R/Project/RData")
load("wordCloud.RData")

pal <- brewer.pal(9, "BuGn")
pal <- pal[-(1:3)]

png("wordcloud.png", width=1280,height=800)
layout(matrix(c(1, 2), nrow=2), heights=c(1, 12))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "Words from Social Media Posts about Protests in China", cex = 3)
graph <- wordcloud(enNames,freq = sorted1000, scale=c(8,.3), max.words = 100, colors = pal,  rot.per=.15)
dev.off()
